import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from './components/NavBar/NavBar'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Geckogen',
  description: 'Generated by create next app',
  icons: {
    icon: "/geckogen-favicon.png"
  }
}

const localization = {
  signIn: {
    start: {
      title: 'Log in'
    }
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body className={inter.className}>
          <NavBar/>
            {children}
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  )
}
